FROM golang:1.23-bullseye AS builder 
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN --mount=type=cache,target="/root/.cache/go-build" GOOS=linux GOARCH=amd64 go build -o /app/server /app/internal/server/server.go

FROM ubuntu:22.04
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/server .
RUN chmod +x /app/server

ENTRYPOINT [ "/app/server" ]
#alpine
#CMD [ "./server" ] 